
Filament Distance from Origin
 ==================== 
Filament Distance from Origin,Unit,Category,Collection,Time,ID,
107244,µm,Filament,Filament Distance from Origin,1,100000000,
109666,µm,Filament,Filament Distance from Origin,1,100000001,
108255,µm,Filament,Filament Distance from Origin,1,100000002,
106858,µm,Filament,Filament Distance from Origin,1,100000003,
107257,µm,Filament,Filament Distance from Origin,1,100000004,
107478,µm,Filament,Filament Distance from Origin,1,100000005,
107578,µm,Filament,Filament Distance from Origin,1,100000006,
107484,µm,Filament,Filament Distance from Origin,1,100000007,
109237,µm,Filament,Filament Distance from Origin,1,100000008,
108253,µm,Filament,Filament Distance from Origin,1,100000009,
106642,µm,Filament,Filament Distance from Origin,1,100000010,
106716,µm,Filament,Filament Distance from Origin,1,100000011,
109908,µm,Filament,Filament Distance from Origin,1,100000012,
108578,µm,Filament,Filament Distance from Origin,1,100000013,
